<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class LaporanWilayah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Auth_model');
        if ($this->session->userdata('is_logged') == true) {
            redirect('Backend', 'refresh');
        }
    }
    
    public function index()
    {
        $this->db->select("cp.kecamatan as kecamatan, 
        SUM(case when kpc.vaksinasi = 'Dosis 1' then 1 else 0 end) as jml_sdh_vaksin_1,
        SUM(case when kpc.vaksinasi = 'Dosis 2' then 1 else 0 end) as jml_sdh_vaksin_2, 
        SUM(case when kpc.nik is null then 1 else 0 end) as jml_blm_vaksin");
        $this->db->from('sync_capil cp');
        $this->db->join('data_kpcpen kpc', 'kpc.nik = cp.nik', 'left');
        $this->db->group_by('cp.kecamatan');
        $dataPerKecamatan = $this->db->get()->result();

        // $this->db->select("cp.kecamatan as id_kecamatan, 
        // SUM(case when kpc.vaksinasi = 'Dosis 1' then 1 else 0 end) as jml_sdh_vaksin_1,
        // SUM(case when kpc.vaksinasi = 'Dosis 2' then 1 else 0 end) as jml_sdh_vaksin_2, 
        // SUM(case when kpc.nik is null then 1 else 0 end) as jml_blm_vaksin");
        // $this->db->from('sync_capil cp');
        // $this->db->join('data_kpcpen kpc', 'kpc.nik = cp.nik', 'left');
        // $this->db->group_by('cp.kecamatan');
        // $dataPerKecamatan = $this->db->get()->result();

        $this->db->select("cp.desa as desa, cp.kecamatan as kecamatan,
        SUM(case when kpc.vaksinasi = 'Dosis 1' then 1 else 0 end) as jml_sdh_vaksin_1,
        SUM(case when kpc.vaksinasi = 'Dosis 2' then 1 else 0 end) as jml_sdh_vaksin_2, 
        SUM(case when kpc.nik is null then 1 else 0 end) as jml_blm_vaksin");
        $this->db->from('sync_capil cp');
        $this->db->join('data_kpcpen kpc', 'kpc.nik = cp.nik', 'left');
        $this->db->group_by('cp.desa');
        $this->db->order_by('cp.kecamatan');
        $dataPerDesa = $this->db->get()->result();



        $this->db->select("cp.desa as desa, cp.kecamatan as kecamatan,
        SUM(case when kpc.vaksinasi = 'Dosis 1' then 1 else 0 end) as jml_sdh_vaksin_1,
        SUM(case when kpc.vaksinasi = 'Dosis 2' then 1 else 0 end) as jml_sdh_vaksin_2, 
        SUM(case when kpc.nik is null then 1 else 0 end) as jml_blm_vaksin");
        $this->db->from('sync_capil cp');
        $this->db->join('data_kpcpen kpc', 'kpc.nik = cp.nik', 'left');
        $this->db->order_by('cp.kecamatan');
        $dataKabupaten = $this->db->get()->result();

        // print_r ($dataPerDesa);die();
        $data = array(
            'content' => 'backend/laporan_wilayah/laporan_wilayah.php',
            'dataPerDesa' => $dataPerDesa,
            'dataPerKecamatan' => $dataPerKecamatan,
            'dataKabupaten' => $dataKabupaten
        );
        $this->load->view('layout_backend.php', $data);
    }
}

/* End of file Kategori.php */
/* Location: ./application/controllers/Kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-02 10:06:01 */
/* http://harviacode.com */