<?php
//Subscribe Youtube Channel Peternak Kode on https://youtube.com/c/peternakkode
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sync_data_bermasalah_model extends CI_Model
{

    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        return $this->db->query("select * from data_bermasalah where nik not in (select nik from data_kpcpen) order by id asc")->result();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $where = "";
        
        if ($q!=''){
            $where = "where (nik like '%$q%' or nama like '%$q%' or alamat like '%$q%' or alamat like '%$q%' or permasalahan like '%$q%' or faskes like '%$q%' or keterangan like '%$q%' or sinkronisasi_dukcapil like '%$q%' perubahan_nik no_hp or like '%$q%')";
        }
        return $this->db->query("select * from data_bermasalah where nik not in (select nik from data_kpcpen) $where")->num_rows();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $where = "";
        $limitoffset = "LIMIT $limit OFFSET $start";
        
        if ($q!=''){
            $where = "where (nik like '%$q%' or nama like '%$q%' or alamat like '%$q%' or alamat like '%$q%' or permasalahan like '%$q%' or faskes like '%$q%' or keterangan like '%$q%' or sinkronisasi_dukcapil like '%$q%' perubahan_nik no_hp or like '%$q%')";
        }
        return $this->db->query("select * from data_bermasalah where nik not in (select nik from data_kpcpen) $where $limitoffset")->result();
    }

    // get data with limit and search data laporan
       // move to bin
    function bin($id)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, array('isactive' => 0));
    }
}

/* End of file Sync_capil_model.php */
/* Location: ./application/models/Sync_capil_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-27 05:06:12 */
/* http://harviacode.com */
/* Customized by Youtube Channel: Peternak Kode (A Channel gives many free codes)*/
/* Visit here: https://youtube.com/c/peternakkode */