<?php
//Subscribe Youtube Channel Peternak Kode on https://youtube.com/c/peternakkode
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbnilaidata_gizi_model extends CI_Model
{
    public $table = '';
    public $id = 'ID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get(getTableProgram(substr($this->session->userdata('id_program'),0,1)))->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get(getTableProgram(substr($this->session->userdata('id_program'),0,1)))->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        // $this->db->where('isactive', 1);
        $this->db->group_start();
        // $this->db->like('', $q);
	$this->db->like('ID', $q);
	$this->db->or_like('NILAI', $q);
	$this->db->or_like('SUMBERDATA', $q);
	$this->db->or_like('KODE', $q);
	$this->db->or_like('TAHUN', $q);
	$this->db->or_like('BULAN', $q);
	$this->db->or_like('PUSKESMAS', $q);
	$this->db->or_like('DESA', $q);
	$this->db->or_like('TGL_ENTRY', $q);
	$this->db->group_end();
    if($this->session->userdata('id_puskesmas')!=""){
        $this->db->where('PUSKESMAS', $this->session->userdata('id_puskesmas'));
        }
            $this->db->from(getTableProgram(substr($this->session->userdata('id_program'),0,1)));
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        // $this->db->select("*,CAST(DESA as CHAR) as DESA");
    $this->db->order_by($this->id, $this->order);
    $this->db->group_start();
	$this->db->like('ID', $q);
	$this->db->or_like('NILAI', $q);
	$this->db->or_like('SUMBERDATA', $q);
	$this->db->or_like('KODE', $q);
	$this->db->or_like('TAHUN', $q);
	$this->db->or_like('BULAN', $q);
	$this->db->or_like('PUSKESMAS', $q);
	$this->db->or_like('DESA', $q);
	$this->db->or_like('TGL_ENTRY', $q);
	$this->db->group_end();
    if($this->session->userdata('id_puskesmas')!=""){
    $this->db->where('PUSKESMAS', $this->session->userdata('id_puskesmas'));
    }
    
    $this->db->limit($limit, $start);
    $this->db->order_by('TGL_ENTRY', 'DESC');
    return $this->db->get(getTableProgram(substr($this->session->userdata('id_program'),0,1)))->result();
    // die($this->db->last_query());
    }

    // insert data
    function insert($data)
    {
        $this->db->insert(getTableProgram(substr($this->session->userdata('id_program'),0,1)), $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update(getTableProgram(substr($this->session->userdata('id_program'),0,1)), $data);
    }

    // delete data
    function delete($id)
    {
        
        $this->db->where($this->id, $id);
        $this->db->delete(getTableProgram(substr($this->session->userdata('id_program'),0,1)));
    }

    // move to bin
    function bin($id){
        $this->db->where($this->id, $id);
        $this->db->update(getTableProgram(substr($this->session->userdata('id_program'),0,1)), array('isactive'=>0));
    }

}

/* End of file Tbnilaidata_gizi_model.php */
/* Location: ./application/models/Tbnilaidata_gizi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-18 01:29:53 */
/* http://harviacode.com */
/* Customized by Youtube Channel: Peternak Kode (A Channel gives many free codes)*/
/* Visit here: https://youtube.com/c/peternakkode */